# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActionMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ActionMessage.proto',
  package='message.action',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x41\x63tionMessage.proto\x12\x0emessage.action\x1a\x19google/protobuf/any.proto\"n\n\rActionMessage\x12\x11\n\tid_sender\x18\x01 \x01(\x05\x12\x12\n\nid_command\x18\x02 \x01(\x05\x12\x10\n\x08id_robot\x18\x03 \x01(\x05\x12$\n\x06\x61\x63tion\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\"\xec\x01\n\x0cMoveLocation\x12\x33\n\x06status\x18\x01 \x01(\x0e\x32#.message.action.MoveLocation.Status\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x39\n\tlocations\x18\x03 \x03(\x0b\x32&.message.action.MoveLocation.Locations\x1a,\n\tLocations\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\"0\n\x06Status\x12\t\n\x05\x41\x42ORT\x10\x00\x12\t\n\x05PAUSE\x10\x01\x12\x08\n\x04STOP\x10\x02\x12\x06\n\x02GO\x10\x03\"X\n\x08MoveBase\x12\x0b\n\x03x_l\x18\x01 \x01(\x05\x12\x0b\n\x03y_l\x18\x02 \x01(\x05\x12\x0b\n\x03z_l\x18\x03 \x01(\x05\x12\x0b\n\x03x_a\x18\x04 \x01(\x05\x12\x0b\n\x03y_a\x18\x05 \x01(\x05\x12\x0b\n\x03z_a\x18\x06 \x01(\x05\"$\n\x0eRobotStartupId\x12\x12\n\nuuid_robot\x18\x01 \x01(\x05\"\xad\x01\n\x07\x41rmMove\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01\x62\x18\x04 \x01(\x02\x12\t\n\x01h\x18\x05 \x01(\x02\x12\t\n\x01l\x18\x06 \x01(\x02\x12\x34\n\tarmaction\x18\x07 \x01(\x0e\x32!.message.action.ArmMove.ArmAction\"*\n\tArmAction\x12\x08\n\x04PICK\x10\x00\x12\t\n\x05PLACE\x10\x01\x12\x08\n\x04HOLD\x10\x02\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])



_MOVELOCATION_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='message.action.MoveLocation.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ABORT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PAUSE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GO', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=367,
  serialized_end=415,
)
_sym_db.RegisterEnumDescriptor(_MOVELOCATION_STATUS)

_ARMMOVE_ARMACTION = _descriptor.EnumDescriptor(
  name='ArmAction',
  full_name='message.action.ArmMove.ArmAction',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PICK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PLACE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HOLD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=677,
  serialized_end=719,
)
_sym_db.RegisterEnumDescriptor(_ARMMOVE_ARMACTION)


_ACTIONMESSAGE = _descriptor.Descriptor(
  name='ActionMessage',
  full_name='message.action.ActionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_sender', full_name='message.action.ActionMessage.id_sender', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id_command', full_name='message.action.ActionMessage.id_command', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id_robot', full_name='message.action.ActionMessage.id_robot', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='message.action.ActionMessage.action', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=176,
)


_MOVELOCATION_LOCATIONS = _descriptor.Descriptor(
  name='Locations',
  full_name='message.action.MoveLocation.Locations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='message.action.MoveLocation.Locations.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='message.action.MoveLocation.Locations.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='message.action.MoveLocation.Locations.z', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=365,
)

_MOVELOCATION = _descriptor.Descriptor(
  name='MoveLocation',
  full_name='message.action.MoveLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='message.action.MoveLocation.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='message.action.MoveLocation.size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='locations', full_name='message.action.MoveLocation.locations', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MOVELOCATION_LOCATIONS, ],
  enum_types=[
    _MOVELOCATION_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=415,
)


_MOVEBASE = _descriptor.Descriptor(
  name='MoveBase',
  full_name='message.action.MoveBase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_l', full_name='message.action.MoveBase.x_l', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y_l', full_name='message.action.MoveBase.y_l', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z_l', full_name='message.action.MoveBase.z_l', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x_a', full_name='message.action.MoveBase.x_a', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y_a', full_name='message.action.MoveBase.y_a', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z_a', full_name='message.action.MoveBase.z_a', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=505,
)


_ROBOTSTARTUPID = _descriptor.Descriptor(
  name='RobotStartupId',
  full_name='message.action.RobotStartupId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid_robot', full_name='message.action.RobotStartupId.uuid_robot', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=507,
  serialized_end=543,
)


_ARMMOVE = _descriptor.Descriptor(
  name='ArmMove',
  full_name='message.action.ArmMove',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='message.action.ArmMove.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='message.action.ArmMove.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='message.action.ArmMove.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='message.action.ArmMove.b', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='h', full_name='message.action.ArmMove.h', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='l', full_name='message.action.ArmMove.l', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='armaction', full_name='message.action.ArmMove.armaction', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ARMMOVE_ARMACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=546,
  serialized_end=719,
)

_ACTIONMESSAGE.fields_by_name['action'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_MOVELOCATION_LOCATIONS.containing_type = _MOVELOCATION
_MOVELOCATION.fields_by_name['status'].enum_type = _MOVELOCATION_STATUS
_MOVELOCATION.fields_by_name['locations'].message_type = _MOVELOCATION_LOCATIONS
_MOVELOCATION_STATUS.containing_type = _MOVELOCATION
_ARMMOVE.fields_by_name['armaction'].enum_type = _ARMMOVE_ARMACTION
_ARMMOVE_ARMACTION.containing_type = _ARMMOVE
DESCRIPTOR.message_types_by_name['ActionMessage'] = _ACTIONMESSAGE
DESCRIPTOR.message_types_by_name['MoveLocation'] = _MOVELOCATION
DESCRIPTOR.message_types_by_name['MoveBase'] = _MOVEBASE
DESCRIPTOR.message_types_by_name['RobotStartupId'] = _ROBOTSTARTUPID
DESCRIPTOR.message_types_by_name['ArmMove'] = _ARMMOVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActionMessage = _reflection.GeneratedProtocolMessageType('ActionMessage', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONMESSAGE,
  '__module__' : 'ActionMessage_pb2'
  # @@protoc_insertion_point(class_scope:message.action.ActionMessage)
  })
_sym_db.RegisterMessage(ActionMessage)

MoveLocation = _reflection.GeneratedProtocolMessageType('MoveLocation', (_message.Message,), {

  'Locations' : _reflection.GeneratedProtocolMessageType('Locations', (_message.Message,), {
    'DESCRIPTOR' : _MOVELOCATION_LOCATIONS,
    '__module__' : 'ActionMessage_pb2'
    # @@protoc_insertion_point(class_scope:message.action.MoveLocation.Locations)
    })
  ,
  'DESCRIPTOR' : _MOVELOCATION,
  '__module__' : 'ActionMessage_pb2'
  # @@protoc_insertion_point(class_scope:message.action.MoveLocation)
  })
_sym_db.RegisterMessage(MoveLocation)
_sym_db.RegisterMessage(MoveLocation.Locations)

MoveBase = _reflection.GeneratedProtocolMessageType('MoveBase', (_message.Message,), {
  'DESCRIPTOR' : _MOVEBASE,
  '__module__' : 'ActionMessage_pb2'
  # @@protoc_insertion_point(class_scope:message.action.MoveBase)
  })
_sym_db.RegisterMessage(MoveBase)

RobotStartupId = _reflection.GeneratedProtocolMessageType('RobotStartupId', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTSTARTUPID,
  '__module__' : 'ActionMessage_pb2'
  # @@protoc_insertion_point(class_scope:message.action.RobotStartupId)
  })
_sym_db.RegisterMessage(RobotStartupId)

ArmMove = _reflection.GeneratedProtocolMessageType('ArmMove', (_message.Message,), {
  'DESCRIPTOR' : _ARMMOVE,
  '__module__' : 'ActionMessage_pb2'
  # @@protoc_insertion_point(class_scope:message.action.ArmMove)
  })
_sym_db.RegisterMessage(ArmMove)


# @@protoc_insertion_point(module_scope)
