# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StatusMessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='StatusMessage.proto',
  package='message.status',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13StatusMessage.proto\x12\x0emessage.status\x1a\x1fgoogle/protobuf/timestamp.proto\"f\n\x04Main\x12(\n\x06status\x18\x01 \x01(\x0b\x32\x16.message.status.StatusH\x00\x12,\n\x08odometry\x18\x02 \x01(\x0b\x32\x18.message.status.OdometryH\x00\x42\x06\n\x04main\"q\n\x06Status\x12\x13\n\x0bid_receiver\x18\x01 \x01(\x05\x12\x12\n\nid_command\x18\x02 \x01(\x05\x12\x10\n\x08id_robot\x18\x03 \x01(\x05\x12,\n\x06status\x18\x04 \x01(\x0e\x32\x1c.message.status.ActionStatus\"\xff\x04\n\x08Odometry\x12\x10\n\x08id_robot\x18\x01 \x01(\x05\x12/\n\x06header\x18\x02 \x01(\x0b\x32\x1f.message.status.Odometry.Header\x12+\n\x04pose\x18\x03 \x01(\x0b\x32\x1d.message.status.Odometry.Pose\x12-\n\x05twist\x18\x04 \x01(\x0b\x32\x1e.message.status.Odometry.Twist\x1aV\n\x06Header\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\t\x1a\xdd\x01\n\x04Pose\x12\x32\n\x05point\x18\x01 \x01(\x0b\x32#.message.status.Odometry.Pose.Point\x12=\n\x0borientation\x18\x02 \x01(\x0b\x32(.message.status.Odometry.Pose.Quaternion\x1a(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1a\x38\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\x1a\x9b\x01\n\x05Twist\x12\x33\n\x06linear\x18\x01 \x01(\x0b\x32#.message.status.Odometry.Twist.Vec3\x12\x34\n\x07\x61ngular\x18\x02 \x01(\x0b\x32#.message.status.Odometry.Twist.Vec3\x1a\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02*U\n\x0c\x41\x63tionStatus\x12\x0b\n\x07PENDING\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x08\n\x04\x44ONE\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x12\x0b\n\x07\x41\x42ORTED\x10\x05\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_ACTIONSTATUS = _descriptor.EnumDescriptor(
  name='ActionStatus',
  full_name='message.status.ActionStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DONE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ABORTED', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=933,
  serialized_end=1018,
)
_sym_db.RegisterEnumDescriptor(_ACTIONSTATUS)

ActionStatus = enum_type_wrapper.EnumTypeWrapper(_ACTIONSTATUS)
PENDING = 0
ACTIVE = 1
DONE = 2
FAILED = 3
ERROR = 4
ABORTED = 5



_MAIN = _descriptor.Descriptor(
  name='Main',
  full_name='message.status.Main',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='message.status.Main.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='odometry', full_name='message.status.Main.odometry', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='main', full_name='message.status.Main.main',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=72,
  serialized_end=174,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='message.status.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_receiver', full_name='message.status.Status.id_receiver', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id_command', full_name='message.status.Status.id_command', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id_robot', full_name='message.status.Status.id_robot', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='message.status.Status.status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=289,
)


_ODOMETRY_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='message.status.Odometry.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='message.status.Odometry.Header.seq', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='message.status.Odometry.Header.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='message.status.Odometry.Header.frame_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=549,
)

_ODOMETRY_POSE_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='message.status.Odometry.Pose.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='message.status.Odometry.Pose.Point.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='message.status.Odometry.Pose.Point.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='message.status.Odometry.Pose.Point.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=675,
  serialized_end=715,
)

_ODOMETRY_POSE_QUATERNION = _descriptor.Descriptor(
  name='Quaternion',
  full_name='message.status.Odometry.Pose.Quaternion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='message.status.Odometry.Pose.Quaternion.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='message.status.Odometry.Pose.Quaternion.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='message.status.Odometry.Pose.Quaternion.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='w', full_name='message.status.Odometry.Pose.Quaternion.w', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=717,
  serialized_end=773,
)

_ODOMETRY_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='message.status.Odometry.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='message.status.Odometry.Pose.point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='message.status.Odometry.Pose.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ODOMETRY_POSE_POINT, _ODOMETRY_POSE_QUATERNION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=773,
)

_ODOMETRY_TWIST_VEC3 = _descriptor.Descriptor(
  name='Vec3',
  full_name='message.status.Odometry.Twist.Vec3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='message.status.Odometry.Twist.Vec3.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='message.status.Odometry.Twist.Vec3.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='message.status.Odometry.Twist.Vec3.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=892,
  serialized_end=931,
)

_ODOMETRY_TWIST = _descriptor.Descriptor(
  name='Twist',
  full_name='message.status.Odometry.Twist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear', full_name='message.status.Odometry.Twist.linear', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angular', full_name='message.status.Odometry.Twist.angular', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ODOMETRY_TWIST_VEC3, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=776,
  serialized_end=931,
)

_ODOMETRY = _descriptor.Descriptor(
  name='Odometry',
  full_name='message.status.Odometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_robot', full_name='message.status.Odometry.id_robot', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='header', full_name='message.status.Odometry.header', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pose', full_name='message.status.Odometry.pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='twist', full_name='message.status.Odometry.twist', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ODOMETRY_HEADER, _ODOMETRY_POSE, _ODOMETRY_TWIST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=931,
)

_MAIN.fields_by_name['status'].message_type = _STATUS
_MAIN.fields_by_name['odometry'].message_type = _ODOMETRY
_MAIN.oneofs_by_name['main'].fields.append(
  _MAIN.fields_by_name['status'])
_MAIN.fields_by_name['status'].containing_oneof = _MAIN.oneofs_by_name['main']
_MAIN.oneofs_by_name['main'].fields.append(
  _MAIN.fields_by_name['odometry'])
_MAIN.fields_by_name['odometry'].containing_oneof = _MAIN.oneofs_by_name['main']
_STATUS.fields_by_name['status'].enum_type = _ACTIONSTATUS
_ODOMETRY_HEADER.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ODOMETRY_HEADER.containing_type = _ODOMETRY
_ODOMETRY_POSE_POINT.containing_type = _ODOMETRY_POSE
_ODOMETRY_POSE_QUATERNION.containing_type = _ODOMETRY_POSE
_ODOMETRY_POSE.fields_by_name['point'].message_type = _ODOMETRY_POSE_POINT
_ODOMETRY_POSE.fields_by_name['orientation'].message_type = _ODOMETRY_POSE_QUATERNION
_ODOMETRY_POSE.containing_type = _ODOMETRY
_ODOMETRY_TWIST_VEC3.containing_type = _ODOMETRY_TWIST
_ODOMETRY_TWIST.fields_by_name['linear'].message_type = _ODOMETRY_TWIST_VEC3
_ODOMETRY_TWIST.fields_by_name['angular'].message_type = _ODOMETRY_TWIST_VEC3
_ODOMETRY_TWIST.containing_type = _ODOMETRY
_ODOMETRY.fields_by_name['header'].message_type = _ODOMETRY_HEADER
_ODOMETRY.fields_by_name['pose'].message_type = _ODOMETRY_POSE
_ODOMETRY.fields_by_name['twist'].message_type = _ODOMETRY_TWIST
DESCRIPTOR.message_types_by_name['Main'] = _MAIN
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Odometry'] = _ODOMETRY
DESCRIPTOR.enum_types_by_name['ActionStatus'] = _ACTIONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Main = _reflection.GeneratedProtocolMessageType('Main', (_message.Message,), {
  'DESCRIPTOR' : _MAIN,
  '__module__' : 'StatusMessage_pb2'
  # @@protoc_insertion_point(class_scope:message.status.Main)
  })
_sym_db.RegisterMessage(Main)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'StatusMessage_pb2'
  # @@protoc_insertion_point(class_scope:message.status.Status)
  })
_sym_db.RegisterMessage(Status)

Odometry = _reflection.GeneratedProtocolMessageType('Odometry', (_message.Message,), {

  'Header' : _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
    'DESCRIPTOR' : _ODOMETRY_HEADER,
    '__module__' : 'StatusMessage_pb2'
    # @@protoc_insertion_point(class_scope:message.status.Odometry.Header)
    })
  ,

  'Pose' : _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), {

    'Point' : _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
      'DESCRIPTOR' : _ODOMETRY_POSE_POINT,
      '__module__' : 'StatusMessage_pb2'
      # @@protoc_insertion_point(class_scope:message.status.Odometry.Pose.Point)
      })
    ,

    'Quaternion' : _reflection.GeneratedProtocolMessageType('Quaternion', (_message.Message,), {
      'DESCRIPTOR' : _ODOMETRY_POSE_QUATERNION,
      '__module__' : 'StatusMessage_pb2'
      # @@protoc_insertion_point(class_scope:message.status.Odometry.Pose.Quaternion)
      })
    ,
    'DESCRIPTOR' : _ODOMETRY_POSE,
    '__module__' : 'StatusMessage_pb2'
    # @@protoc_insertion_point(class_scope:message.status.Odometry.Pose)
    })
  ,

  'Twist' : _reflection.GeneratedProtocolMessageType('Twist', (_message.Message,), {

    'Vec3' : _reflection.GeneratedProtocolMessageType('Vec3', (_message.Message,), {
      'DESCRIPTOR' : _ODOMETRY_TWIST_VEC3,
      '__module__' : 'StatusMessage_pb2'
      # @@protoc_insertion_point(class_scope:message.status.Odometry.Twist.Vec3)
      })
    ,
    'DESCRIPTOR' : _ODOMETRY_TWIST,
    '__module__' : 'StatusMessage_pb2'
    # @@protoc_insertion_point(class_scope:message.status.Odometry.Twist)
    })
  ,
  'DESCRIPTOR' : _ODOMETRY,
  '__module__' : 'StatusMessage_pb2'
  # @@protoc_insertion_point(class_scope:message.status.Odometry)
  })
_sym_db.RegisterMessage(Odometry)
_sym_db.RegisterMessage(Odometry.Header)
_sym_db.RegisterMessage(Odometry.Pose)
_sym_db.RegisterMessage(Odometry.Pose.Point)
_sym_db.RegisterMessage(Odometry.Pose.Quaternion)
_sym_db.RegisterMessage(Odometry.Twist)
_sym_db.RegisterMessage(Odometry.Twist.Vec3)


# @@protoc_insertion_point(module_scope)
